### PR TITLE
fix: deprecation warning for collection.update when user overrides update method

### PR DESCRIPTION
**Pull request by nsine**
This PR https://github.com/dsanel/mongoose-delete/pull/56 meant to fix this annoying `DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.` message from mongoose. 
However if you override `update` method - the code still relies on `.updateWithDeleted` method despite version of mongoose which uses `.update` under the hood.
So this PR fixes it and makes it to use `updateManyWithDeleted` in case of mongoose v5.x

PS closes https://github.com/dsanel/mongoose-delete/issues/78

### CODE REVIEW

**Comment by nishant-lambdaschool** [comment]
This needs to be merged.

**Comment by devop911** [comment]
Ofc, please merge it

**Comment by alexandre-okidoo** [comment]
Is there anything left to do for this to be merged?

**Comment by perebusquets** [comment]
Why isn't this merged already...?

**Comment by dsanel** [comment]
[v0.5.3](https://github.com/dsanel/mongoose-delete/blob/master/CHANGELOG.md#v053)

**Comment by nsine** [comment]
thanks @dsanel 🙏

**Pull request closed without merging**
