### PR TITLE
Fix Mongoose DeprecationWarning: collection.update is deprecated

### PR DESCRIPTION
**Pull request by cardimajs**

### CODE REVIEW

**Comment by jebarjonet** [comment]
@cardimajs those should use `updateMany` instead of `updateOne` no?

**Comment by cardimajs** [comment]
@jebarjonet yes tanks.

**Comment by israelglar** [comment]
Is this being pulled any time soon?

**Comment by natenrb9** [comment]
Please pull this commit and update. Thanks.

**Comment by dsanel** [comment]
https://github.com/dsanel/mongoose-delete/blob/master/CHANGELOG.md#v051

Thanks for help @cardimajs @jebarjonet

**Pull request closed without merging**
