### PR TITLE
override aggregate

### PR DESCRIPTION
**Pull request by shimonbrandsdorfer**

### CODE REVIEW

**Comment by dsanel** [comment]
Hi @shimonbrandsdorfer,

this PR looks very promising but I have several items:
1. Why do we need [this](https://github.com/dsanel/mongoose-delete/pull/31/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R32)? Any specific reason?
```
"dependencies": {
   "mongoose": "4.x"
},
```

2. Can you please provide simple README documentation and examples for new features (`aggregate`)?

3. Can you use identical code formatting as we already use in code? Overall it is very good and clean, but I notice several wrong spaces, empty spaces...

**Comment by shimonbrandsdorfer** [comment]
Hi @dsanel,
Pardon my ignorance. It's my first commit to an open-source project. (I would ignore the package.json file, I just didn't know how to do it).

**Comment by dsanel** [comment]
Please do not worry @shimonbrandsdorfer, this is not any big mistake or problem just small tricks how to keep module clean and in good shape. :)

You can just do all your changes in this `branch` and push it to GitHub.

**Comment by gfviegas** [comment]
Any update on this @dsanel ?

**Comment by menocomp** [comment]
any update on this? ^^^

**Comment by kenzdozz** [comment]
Hi @dsanel , what can be done for this to get merged??

**Comment by RsknCankov** [comment]
@dsanel can we give you a hand with this one in order to be merged ?

**Comment by RsknCankov** [comment]
Guys, I managed to fork with the changes from this PR and basically it seems implementation of overwriting aggregate. Executing following aggregation 
`aggregate([
            {$project: {name: 1, deleted: 1}},
        ]`
 resulting in
 `[
  {
    _id: 5e847e4f9ef53316905cc0fa,
    deleted: true,
    name: 'Obi-Wan Kenobi'
  },
  {
    _id: 5e847e4f9ef53316905cc0fb,
    deleted: false,
    name: 'Darth Vader'
  },
  {
    _id: 5e847e4f9ef53316905cc0fc,
    deleted: false,
    name: 'Luke Skywalker'
  }
]`

I am trying to figure out what is the problem, but it would be useful if someone give me a hand on that.
Cheers!

**Comment by dsanel** [comment]
Hello, everyone! I was very busy the last several months, didn't be able to spend some good time on this. I want to inform you that we have a new `0.5.2` version of this plugin with support for the `aggregate` override. 

I reuse some code from this PR and some extra code and features too. Now we will be able to use a pipeline builder too.

```
        TestModel.aggregate([
            {
                $project : { name : 1 }
            }
        ], function (err, documents) {
            should.not.exist(err);
            documents.length.should.equal(1);
            done();
        });
```
or this way
```
        TestModel
            .aggregate()
            .project({ name : 1 })
            .exec(function (err, documents) {
                should.not.exist(err);
                documents.length.should.equal(1);
                done();
            });

        TestModel
          .aggregateDeleted()
          .project({ name : 1 })
          .exec(function (err, documents) {
              should.not.exist(err);
              documents.length.should.equal(2);
              done();
          });
```

Anyway, I want to tanks to @shimonbrandsdorfer for his first commit related to this feature. And everyone else for all other support and comments.

**Comment by dsanel** [comment]
https://github.com/dsanel/mongoose-delete/commit/79d7f611bd47238ecd02feb3b87b96c84c060673

**Pull request closed without merging**
