### PR TITLE
Added indexes to deleted, deletedAt, deletedBy

### PR DESCRIPTION
**Pull request by rdiaztushman**

### CODE REVIEW

**Comment by rdiaztushman** [comment]
Here's a PR with the current version of the plugin that we're using

**Comment by rdiaztushman** [comment]
Weird.  Why did coverage decrease like that, @dsanel ?

**Comment by dsanel** [comment]
I will check it! ;)

I will merge PR #11 but for this PR we need to create additional option. We can use option `indexDeleteFields` or similar so a user can decide to index or not those fields.

I will work on this later today ;)

**Comment by rdiaztushman** [comment]
Ok.  Sounds good for "deletedBy" and "deletedAt", so I would make those optional, but I can't imagine a scenario where a user would NOT want to index the "deleted" field (since this plugin forces every query to filter against it) so I wouldn't bother creating an option for that field.

**Comment by dsanel** [comment]
I understand you point, but this plugin is used by big number or users and it will be very irresponsible to force all users to reindex any field. Mongoose automatically calls `ensureIndex` for each defined index in your schema and if a user does not disable this option it can make unwanted changes...

I will create options for all three fields and it will be best for everyone. I believe that you will like the solution. ;)

**Comment by dsanel** [comment]
We have new version!

**Pull request closed without merging**
